[package]
name = "viewshopdrawings"
version = "0.1.0"
authors = ["paddymills <paddymills@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitfailure = "0.5.1"
lazy_static = "1.4.0"
regex = "1.3.9"
structopt = "0.3.15"
winreg = "0.7.0"
