[package]
name = "hsspdfopen"
version = "0.1.0"
authors = ["paddymills <paddymills@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitfailure = "0.5"
lazy_static = "1.4"
open = "3.0"
opener = "0.5"
regex = "1.6"
structopt = "0.3"
winreg = "0.10.1"
